site_name: stac-fastapi-sqlalchemy
site_description: STAC FastAPI - sqlalchemy backend.

# Repository
repo_name: "stac-utils/stac-fastapi-sqlalchemy"
repo_url: "https://github.com/stac-utils/stac-fastapi-sqlalchemy"
edit_uri: "blob/master/docs/src/"

# Social links
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/stac-utils"

# Layout
nav:
  - Home: "index.md"
  - API:
      - stac_fastapi.sqlalchemy:
          - extensions:
              - index: api/stac_fastapi/sqlalchemy/extensions/index.md
              - query: api/stac_fastapi/sqlalchemy/extensions/query.md
          - models:
              - database: api/stac_fastapi/sqlalchemy/models/database.md
              - index: api/stac_fastapi/sqlalchemy/models/index.md
              - search: api/stac_fastapi/sqlalchemy/models/search.md
          - app: api/stac_fastapi/sqlalchemy/app.md
          - config: api/stac_fastapi/sqlalchemy/config.md
          - core: api/stac_fastapi/sqlalchemy/core.md
          - index: api/stac_fastapi/sqlalchemy/index.md
          - serializers: api/stac_fastapi/sqlalchemy/serializers.md
          - session: api/stac_fastapi/sqlalchemy/session.md
          - tokens: api/stac_fastapi/sqlalchemy/tokens.md
          - transactions: api/stac_fastapi/sqlalchemy/transactions.md
          - version: api/stac_fastapi/sqlalchemy/version.md
  - Development - Contributing: "contributing.md"
  - Release Notes: "release-notes.md"

plugins:
  - search

# Theme
theme:
  icon:
    logo: "material/home"
    repo: "fontawesome/brands/github"
  name: "material"
  language: "en"
  font:
    text: "Nunito Sans"
    code: "Fira Code"

extra_css:
  - stylesheets/extra.css

# These extensions are chosen to be a superset of Pandoc's Markdown.
# This way, I can write in Pandoc's Markdown and have it be supported here.
# https://pandoc.org/MANUAL.html
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret:
      insert: false
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
